export const INIT_APP = 'INIT_APP';
export const SET_AVATAR_PATH = 'SET_AVATAR_PATH';
export const UPDATE_REGISTRATION_STATUS = 'UPDATE_REGISTRATION_STATUS';
export const SAVE_USER_ID = 'SAVE_USER_ID';
export const SAVE_USER_IMEI = 'SAVE_USER_IMEI';
export const SAVE_USER_PASSWORD = 'SAVE_USER_PASSWORD';
export const SAVE_USER_PHONE = 'SAVE_USER_PHONE';
export const SAVE_USER_TOKEN = 'SAVE_USER_TOKEN';
